language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
- mongodb
- redis-server

before_script:




after_success:



after_failure:

notifications:
email:
- yang_ping01@easyway.net.cn
on_success: change
